language: perl
# v0.012_000

addons:
    apt:
        packages:
            - astyle

perl:
    - "5.8"
    - "5.10"
    - "5.12"
    - "5.14"
    - "5.16"
    - "5.18"
    - "5.20"
    - "5.22"
    - "5.24"
    # version(s) below are built using Travis-CI Helper
    - "5.25" 
#    - "dev"  # same as 5.25 above
    - "blead"

# [ BEGIN Travis-CI Helper ]
matrix:
    allow_failures:
        - perl: "blead"
before_install:
    - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
    - source ~/travis-perl-helpers/init
    - build-perl
    - perl -V

# NEED UPGRADE: use build-dist instead of cpanm calls below?
#    - build-dist
#    - cd $BUILD_DIR             # $BUILD_DIR is set by the build-dist command
# [ END Travis-CI Helper ]

install:
    # DEV NOTE, CORRELATION #aa001: must install IO::Socket::SSL & Alien::Base::ModuleBuild from Build.PL (which becomes META.json, for CPAN) & .travis.yml & appveyor.yml 
    - cpanm --verbose IO::Socket::SSL
    - cpanm --verbose Alien::Base::ModuleBuild
    - cpanm --verbose --installdeps .

script:
    - perl Build.PL
    - ./Build
    - ./Build test
    - ./Build install
    - perl -e 'use Alien::astyle; use Env qw(@PATH); unshift @PATH, Alien::astyle->bin_dir(); print `astyle --version`, "\n";'

notifications:
  irc:
    channels:
        - "irc.perl.org#perl11"
    on_success: always
    on_failure: always
    # to enable skip_join, in IRC channel first execute `/mode -n`
    skip_join: true
    template:
        - "Alien::astyle build %{result}. %{author} says '%{commit_message}'"
        - "%{build_url} %{compare_url}"

env:
    global:
        - AUTHOR_TESTING=0
    matrix:
        - ALIEN_INSTALL_TYPE=share
        - ALIEN_INSTALL_TYPE=system
