language: perl
# v0.004_000

perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"

install:
    # NEED ANSWER: why isn't A::B::MB auto-installed by --installdeps?
    - cpanm Alien::Base::ModuleBuild
    - cpanm --verbose --installdeps .

script:
    - perl Build.PL
    - ./Build
    - ./Build test
    - ./Build install
    - perl -e 'use Alien::astyle; use Env qw(@PATH); unshift @PATH, Alien::astyle->bin_dir(); print `astyle --version`, "\n";'

notifications:
  irc:
    channels:
      - "irc.perl.org#perl11"
    on_success: always
    on_failure: always
    # to enable skip_join, in IRC channel first execute `/mode -n`
    skip_join: true
    template:
      - "Alien::astyle build %{result}. %{author} says '%{commit_message}'"
      - "%{build_url} %{compare_url}"
