language: perl
# v0.001_000

perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"

install:
    - cpanm --verbose --installdeps .

script:
    - perl Build.PL
    - Build
    - Build test

notifications:
  irc:
    channels:
      - "irc.perl.org#perl11"
    on_success: always
    on_failure: always
    # to enable skip_join, in IRC channel first execute `/mode -n`
    skip_join: true
    template:
      - "Alien::astyle build %{result}. %{author} says '%{commit_message}'"
      - "%{build_url} %{compare_url}"
