# v0.005_000
version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: false
skip_tags: true
clone_depth: 1
clone_folder: C:\projects\alien-astyle

environment:
    matrix:
        # share test, compile astyle from source
        - ALIEN_INSTALL_TYPE: share

        # system test, uses astyle from chocolatey
        - ALIEN_INSTALL_TYPE: system

install:
- cmd: >-

    choco install astyle

    astyle --version

    choco install curl

    curl -V

    curl -O http://strawberryperl.com/download/5.24.0.1/strawberry-perl-5.24.0.1-32bit.msi

    msiexec /i strawberry-perl-5.24.0.1-32bit.msi /quiet /qn /norestart

    set PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;C:\windows\system32;C:\windows;

    gcc -v

    g++ -v

    perl -V

    cpanm --verbose Alien::Base::ModuleBuild

    perl Build.PL

    perl -e"require CPAN;CPAN::Shell->notest('install','App::cpanminus');"

    cpanm --verbose --installdeps .

    set PERL5LIB=blib;lib

    set

    perl -le "print for @INC"

    Build test
build: off
test: off
deploy: off
