# v0.019_000
version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: false
skip_tags: true
clone_depth: 1
clone_folder: C:\projects\alien-astyle

environment:
    matrix:
        # share test, compile astyle from source
        - ALIEN_INSTALL_TYPE: share

        # system test, uses astyle from chocolatey
#        - ALIEN_INSTALL_TYPE: system

# DEV NOTE, CORRELATION #aa001: must install IO::Socket::SSL & Alien::Base::ModuleBuild from Build.PL (which becomes META.json, for CPAN) & .travis.yml & appveyor.yml 
install:
- cmd: >-

    choco install astyle

    astyle --version

    where.exe astyle.exe

    set PATH_FULL=%path%

    echo %PATH_FULL%

    choco install curl

    curl -V

    curl -O http://strawberryperl.com/download/5.24.0.1/strawberry-perl-5.24.0.1-32bit.msi

    msiexec /i strawberry-perl-5.24.0.1-32bit.msi /quiet /qn /norestart

    set PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;C:\windows\system32;C:\windows;

    gcc -v

    g++ -v

    perl -V

    perl -e"require CPAN;CPAN::Shell->verbose('install','App::cpanminus');"

    echo pre-gmake ALIEN_INSTALL_TYPE = %ALIEN_INSTALL_TYPE%

    set ALIEN_INSTALL_TYPE_TMP=%ALIEN_INSTALL_TYPE%

    set ALIEN_INSTALL_TYPE=system

    echo gmake ALIEN_INSTALL_TYPE = %ALIEN_INSTALL_TYPE%

    cpanm --notest Alien::MSYS

    cpanm --notest Alien::gmake

    set ALIEN_INSTALL_TYPE=%ALIEN_INSTALL_TYPE_TMP%

    echo post-gmake ALIEN_INSTALL_TYPE = %ALIEN_INSTALL_TYPE%

    cpanm --notest IO::Socket::SSL

    curl -O https://github.com/wbraswell/Alien-Base/archive/master.zip

    unzip master.zip

    cd Alien-Base*

    perl Build.PL

    Build test

    Build install

    cpanm --verbose Alien::Base::ModuleBuild

    perl Build.PL

    cpanm --notest --installdeps .

    set PERL5LIB=blib;lib

    set

    perl -le "print for @INC"

    Build test
build: off
test: off
deploy: off
